const { expect } = require('chai')
const { parseEther } = require('ethers/lib/utils')
const { ethers } = require('hardhat')

describe('ERC1155 NFT Marketplace Smart Contract', () => {
  let Custom1155Factory, AddressesFactory, MarketplaceFactory, ProxyFactory, SparkTokenFactory, ArrayLibraryFactory
  let custom1155, addresses, marketplace, proxy, sparkToken, arrayLibrary
  let accounts
  let nftPrice = parseEther('1.0')
  let nftEndPrice = parseEther('0.5')
  let offerPrice1 = parseEther('0.8')
  let offerPrice2 = parseEther('0.9')

  before(async () => {
    accounts = await ethers.getSigners()

    AddressesFactory = await ethers.getContractFactory('Addresses')
    ArrayLibraryFactory = await ethers.getContractFactory('ArrayLibrary')
    arrayLibrary = await ArrayLibraryFactory.connect(accounts[0]).deploy()
    MarketplaceFactory = await ethers.getContractFactory('ERC1155Marketplace', { libraries: { ArrayLibrary: arrayLibrary.address } })
    Custom1155Factory = await ethers.getContractFactory('Custom1155')
    ProxyFactory = await ethers.getContractFactory('ProxyRegistry')
    SparkTokenFactory = await ethers.getContractFactory('SparksToken')
  })

  beforeEach(async () => {
    addresses = await AddressesFactory.connect(accounts[0]).deploy()
    await addresses.deployed()
    sparkToken = await SparkTokenFactory.connect(accounts[3]).deploy()
    await sparkToken.deployed()
    marketplace = await MarketplaceFactory.connect(accounts[0]).deploy()
    await marketplace.deployed()
    await (await marketplace.setSparkTokenContractAddr(sparkToken.address)).wait()
    proxy = await ProxyFactory.deploy()
    await proxy.deployed()
    proxy.connect(accounts[0]).setProxy(marketplace.address)
    custom1155 = await Custom1155Factory.deploy(proxy.address)
    await custom1155.deployed()
    await (await custom1155.connect(accounts[0]).mint('path1', 10)).wait()
  })

  it('Check ERC1155 NFT', async () => {
    expect(await custom1155.balanceOf(accounts[0].address, 1)).to.equal(10)
    expect(await custom1155.uri(1)).to.equal('path1')
  })

  it('Check Addresses Contract in Marketplace', async () => {
    expect(await marketplace.addressesContractAddr()).to.equal('0x0000000000000000000000000000000000000000')
    await (await marketplace.connect(accounts[0]).setAddressesContractAddr(addresses.address)).wait()
    expect(await marketplace.addressesContractAddr()).to.equal(addresses.address)
  })

  it('Check Adding, Verifying and Removing ERC1155 NFT in Addresses', async () => {
    expect(await addresses.existingContract(custom1155.address)).to.equal(false)
    await expect(addresses.isVerified(custom1155.address)).to.be.revertedWith('Not Existing Contract')
    let multiTokenContracts = await addresses.getMultiTokenContracts()
    let verifiedContracts = await addresses.getVerifiedMultiTokenContracts()
    expect(multiTokenContracts.length).to.equal(0)
    expect(verifiedContracts.length).to.equal(0)
    await (await addresses.connect(accounts[0]).add(custom1155.address)).wait()
    expect(await addresses.existingContract(custom1155.address)).to.equal(true)
    multiTokenContracts = await addresses.getMultiTokenContracts()
    expect(multiTokenContracts.length).to.equal(1)
    expect(multiTokenContracts[0]).to.equal(custom1155.address)
    verifiedContracts = await addresses.getVerifiedMultiTokenContracts()
    expect(verifiedContracts.length).to.equal(0)
    await expect(addresses.add(custom1155.address)).to.be.revertedWith('Exisitng Contract')
    await (await addresses.verify(custom1155.address)).wait()
    expect(await addresses.isVerified(custom1155.address)).to.equal(true)
    verifiedContracts = await addresses.getVerifiedMultiTokenContracts()
    expect(verifiedContracts.length).to.equal(1)
    expect(verifiedContracts[0]).to.equal(custom1155.address)
    await (await addresses.connect(accounts[0]).remove(custom1155.address)).wait()
    multiTokenContracts = await addresses.getMultiTokenContracts()
    verifiedContracts = await addresses.getVerifiedMultiTokenContracts()
    expect(multiTokenContracts.length).to.equal(0)
    expect(verifiedContracts.length).to.equal(0)
  })

  it('Create Sale and Cancel Sale with Verified ERC1155 NFT Smart Contract', async () => {
    await (await marketplace.connect(accounts[0]).setAddressesContractAddr(addresses.address)).wait()
    await (await addresses.add(custom1155.address)).wait()
    await (await addresses.verify(custom1155.address)).wait()
    let verifiedContracts = await addresses.getVerifiedMultiTokenContracts()
    expect(verifiedContracts.length).to.equal(1)
    expect(verifiedContracts[0]).to.equal(custom1155.address)
    let saleTokens = await marketplace.getSaleTokens(custom1155.address)
    expect(saleTokens.length).to.equal(0)
    let saleTokensBySeller = await marketplace.getSaleTokensBySeller(custom1155.address, accounts[0].address)
    expect(saleTokensBySeller.length).to.equal(0)
    let sales = await marketplace.getSalesByNFT(custom1155.address, 1)
    expect(sales.sales.length).to.equal(0)
    await (await marketplace.connect(accounts[0]).createSale(custom1155.address, 1, 1, nftPrice.toString(), nftEndPrice.toString(), 1000, 5)).wait()
    expect(await custom1155.balanceOf(accounts[0].address, 1)).to.equal(5)
    saleTokens = await marketplace.getSaleTokens(custom1155.address)
    expect(saleTokens.length).to.equal(1)
    expect(saleTokens[0]).to.equal('1')
    saleTokensBySeller = await marketplace.getSaleTokensBySeller(custom1155.address, accounts[0].address)
    expect(saleTokensBySeller.length).to.equal(1)
    expect(saleTokensBySeller[0]).to.equal('1')
    sales = await marketplace.getSalesByNFT(custom1155.address, 1)
    expect(sales.sales.length).to.equal(1)
    expect(sales.sales[0].payment.toString()).to.equal('1')
    expect(sales.sales[0].seller).to.equal(accounts[0].address)
    expect(sales.sales[0].startPrice.toString()).to.equal(nftPrice.toString())
    expect(sales.sales[0].endPrice.toString()).to.equal(nftEndPrice.toString())
    expect(sales.sales[0].amount.toString()).to.equal('5')
    expect(sales.sales[0].duration.toString()).to.equal('1000')
    await (await marketplace.connect(accounts[0]).cancelSale(custom1155.address, 1, sales.sales[0].seller, 1, sales.sales[0].startPrice, sales.sales[0].endPrice, 2, sales.sales[0].startedAt, sales.sales[0].duration)).wait()
    saleTokens = await marketplace.getSaleTokens(custom1155.address)
    expect(saleTokens.length).to.equal(1)
    expect(saleTokens[0]).to.equal('1')
    saleTokensBySeller = await marketplace.getSaleTokensBySeller(custom1155.address, accounts[0].address)
    expect(saleTokensBySeller.length).to.equal(1)
    expect(saleTokensBySeller[0]).to.equal('1')
    sales = await marketplace.getSalesByNFT(custom1155.address, 1)
    expect(sales.sales.length).to.equal(1)
    expect(sales.sales[0].payment.toString()).to.equal('1')
    expect(sales.sales[0].seller).to.equal(accounts[0].address)
    expect(sales.sales[0].startPrice.toString()).to.equal(nftPrice.toString())
    expect(sales.sales[0].endPrice.toString()).to.equal(nftEndPrice.toString())
    expect(sales.sales[0].amount.toString()).to.equal('3')
    expect(sales.sales[0].duration.toString()).to.equal('1000')
    expect(await custom1155.balanceOf(accounts[0].address, '1')).to.equal(7)
    await (await marketplace.connect(accounts[0]).cancelSale(custom1155.address, 1, sales.sales[0].seller, 1, sales.sales[0].startPrice, sales.sales[0].endPrice, 3, sales.sales[0].startedAt, sales.sales[0].duration)).wait()
    saleTokens = await marketplace.getSaleTokens(custom1155.address)
    expect(saleTokens.length).to.equal(0)
    saleTokensBySeller = await marketplace.getSaleTokensBySeller(custom1155.address, accounts[0].address)
    expect(saleTokensBySeller.length).to.equal(0)
    sales = await marketplace.getSalesByNFT(custom1155.address, 1)
    expect(sales.sales.length).to.equal(0)
    expect(await custom1155.balanceOf(accounts[0].address, '1')).to.equal(10)
  })

  it('Create Sale and Purchase Sale with Verified ERC1155 NFT Smart Contract', async () => {
    await (await marketplace.connect(accounts[0]).setAddressesContractAddr(addresses.address)).wait()
    await (await addresses.add(custom1155.address)).wait()
    await (await addresses.verify(custom1155.address)).wait()
    let saleTokens = await marketplace.getSaleTokens(custom1155.address)
    expect(saleTokens.length).to.equal(0)
    let saleTokensBySeller = await marketplace.getSaleTokensBySeller(custom1155.address, accounts[0].address)
    expect(saleTokensBySeller.length).to.equal(0)
    let sales = await marketplace.getSalesByNFT(custom1155.address, 1)
    expect(sales.sales.length).to.equal(0)
    let salesBySellerNFT = await marketplace.getSalesBySellerNFT(accounts[0].address, custom1155.address, 1)
    expect(salesBySellerNFT.sales.length).to.equal(0)
    await (await marketplace.connect(accounts[0]).createSale(custom1155.address, 1, 1, nftPrice.toString(), nftEndPrice.toString(), 1000, 5)).wait()
    expect(await custom1155.balanceOf(accounts[0].address, 1)).to.equal(5)
    sales = await marketplace.getSalesByNFT(custom1155.address, 1)
    expect(sales.sales.length).to.equal(1)
    expect(sales.sales[0].payment.toString()).to.equal('1')
    expect(sales.sales[0].seller).to.equal(accounts[0].address)
    expect(sales.sales[0].startPrice.toString()).to.equal(nftPrice.toString())
    expect(sales.sales[0].endPrice.toString()).to.equal(nftEndPrice.toString())
    expect(sales.sales[0].amount.toString()).to.equal('5')
    expect(sales.sales[0].duration.toString()).to.equal('1000')
    saleTokens = await marketplace.getSaleTokens(custom1155.address)
    expect(saleTokens.length).to.equal(1)
    expect(saleTokens[0]).to.equal('1')
    saleTokensBySeller = await marketplace.getSaleTokensBySeller(custom1155.address, accounts[0].address)
    expect(saleTokensBySeller.length).to.equal(1)
    expect(saleTokensBySeller[0]).to.equal('1')
    let currentPrice = await marketplace.getCurrentPrice(custom1155.address, 1, { payment: 1, seller: sales.sales[0].seller, startPrice: sales.sales[0].startPrice, endPrice: sales.sales[0].endPrice, amount: 1, startedAt: sales.sales[0].startedAt, duration: sales.sales[0].duration })
    expect(currentPrice.lte(nftPrice)).to.equal(true)
    expect(currentPrice.gte(nftEndPrice)).to.equal(true)
    let prevBalance = await accounts[0].getBalance()
    let buyRes = await (await marketplace.connect(accounts[1]).buy(custom1155.address, 1, sales.sales[0].seller, 1, sales.sales[0].startPrice, sales.sales[0].endPrice, 2, sales.sales[0].startedAt, sales.sales[0].duration, {
      from: accounts[1].address,
      value: currentPrice.mul(2)
    })).wait()
    let saleSuccessEvent = buyRes.events.find(event => event.event === 'SaleSuccessful')
    let afterBalance = await accounts[0].getBalance()
    expect(afterBalance.sub(prevBalance).eq(saleSuccessEvent.args.price)).to.equal(true)
    expect(await custom1155.balanceOf(accounts[1].address, 1)).to.equal(2)
    sales = await marketplace.getSalesByNFT(custom1155.address, 1)
    expect(sales.sales.length).to.equal(1)
    expect(sales.sales[0].payment.toString()).to.equal('1')
    expect(sales.sales[0].seller).to.equal(accounts[0].address)
    expect(sales.sales[0].startPrice.toString()).to.equal(nftPrice.toString())
    expect(sales.sales[0].endPrice.toString()).to.equal(nftEndPrice.toString())
    expect(sales.sales[0].amount.toString()).to.equal('3')
    expect(sales.sales[0].duration.toString()).to.equal('1000')
    saleTokens = await marketplace.getSaleTokens(custom1155.address)
    expect(saleTokens.length).to.equal(1)
    expect(saleTokens[0]).to.equal('1')
    saleTokensBySeller = await marketplace.getSaleTokensBySeller(custom1155.address, accounts[0].address)
    expect(saleTokensBySeller.length).to.equal(1)
    expect(saleTokensBySeller[0]).to.equal('1')
    salesBySellerNFT = await marketplace.getSalesBySellerNFT(accounts[0].address, custom1155.address, 1)
    expect(salesBySellerNFT.sales.length).to.equal(1)
    expect(salesBySellerNFT.sales[0].payment.toString()).to.equal('1')
    expect(salesBySellerNFT.sales[0].startPrice.toString()).to.equal(nftPrice.toString())
    expect(salesBySellerNFT.sales[0].endPrice.toString()).to.equal(nftEndPrice.toString())
    expect(salesBySellerNFT.sales[0].amount.toString()).to.equal('3')
    expect(salesBySellerNFT.sales[0].duration.toString()).to.equal('1000')
    currentPrice = await marketplace.getCurrentPrice(custom1155.address, 1, { payment: 1, seller: sales.sales[0].seller, startPrice: sales.sales[0].startPrice, endPrice: sales.sales[0].endPrice, amount: 1, startedAt: sales.sales[0].startedAt, duration: sales.sales[0].duration })
    expect(currentPrice.lte(nftPrice)).to.equal(true)
    expect(currentPrice.gte(nftEndPrice)).to.equal(true)
    prevBalance = await accounts[0].getBalance()
    buyRes = await (await marketplace.connect(accounts[1]).buy(custom1155.address, 1, sales.sales[0].seller, 1, sales.sales[0].startPrice, sales.sales[0].endPrice, 3, sales.sales[0].startedAt, sales.sales[0].duration, {
      from: accounts[1].address,
      value: currentPrice.mul(3)
    })).wait()
    saleSuccessEvent = buyRes.events.find(event => event.event === 'SaleSuccessful')
    afterBalance = await accounts[0].getBalance()
    expect(afterBalance.sub(prevBalance).eq(saleSuccessEvent.args.price)).to.equal(true)
    expect(await custom1155.balanceOf(accounts[1].address, 1)).to.equal(5)
    sales = await marketplace.getSalesByNFT(custom1155.address, 1)
    expect(sales.sales.length).to.equal(0)
    saleTokens = await marketplace.getSaleTokens(custom1155.address)
    expect(saleTokens.length).to.equal(0)
    saleTokensBySeller = await marketplace.getSaleTokensBySeller(custom1155.address, accounts[0].address)
    expect(saleTokensBySeller.length).to.equal(0)
    salesBySellerNFT = await marketplace.getSalesBySellerNFT(accounts[0].address, custom1155.address, 1)
    expect(salesBySellerNFT.sales.length).to.equal(0)
  })

  it('Create Sale, Create Offer and Cancel Offer with Verified ERC1155 NFT Smart Contract', async () => {
    await (await marketplace.connect(accounts[0]).setAddressesContractAddr(addresses.address)).wait()
    await (await addresses.add(custom1155.address)).wait()
    await (await addresses.verify(custom1155.address)).wait()
    let saleTokens = await marketplace.getSaleTokens(custom1155.address)
    expect(saleTokens.length).to.equal(0)
    let saleTokensBySeller = await marketplace.getSaleTokensBySeller(custom1155.address, accounts[0].address)
    expect(saleTokensBySeller.length).to.equal(0)
    let sales = await marketplace.getSalesByNFT(custom1155.address, 1)
    expect(sales.sales.length).to.equal(0)
    let salesBySellerNFT = await marketplace.getSalesBySellerNFT(accounts[0].address, custom1155.address, 1)
    expect(salesBySellerNFT.sales.length).to.equal(0)
    await (await marketplace.connect(accounts[0]).createSale(custom1155.address, 1, 1, nftPrice.toString(), nftEndPrice.toString(), 1000, 5)).wait()
    expect(await custom1155.balanceOf(accounts[0].address, 1)).to.equal(5)
    sales = await marketplace.getSalesByNFT(custom1155.address, 1)
    expect(sales.sales.length).to.equal(1)
    expect(sales.sales[0].payment.toString()).to.equal('1')
    expect(sales.sales[0].seller).to.equal(accounts[0].address)
    expect(sales.sales[0].startPrice.toString()).to.equal(nftPrice.toString())
    expect(sales.sales[0].endPrice.toString()).to.equal(nftEndPrice.toString())
    expect(sales.sales[0].amount.toString()).to.equal('5')
    expect(sales.sales[0].duration.toString()).to.equal('1000')
    let prevBalance = await accounts[1].getBalance()
    let txRes = await (await marketplace.connect(accounts[1]).makeOffer(custom1155.address, 1, sales.sales[0].seller, 1, nftPrice.toString(), nftEndPrice.toString(), sales.sales[0].startedAt, 1000, offerPrice1, 2, {
      from: accounts[1].address,
      value: offerPrice1.mul(2)
    })).wait()
    let afterBalance = await accounts[1].getBalance()
    expect(prevBalance.sub(txRes.cumulativeGasUsed.mul(txRes.effectiveGasPrice))).to.equal(afterBalance.add(offerPrice1.mul(2)))
    prevBalance = await accounts[2].getBalance()
    txRes = await (await marketplace.connect(accounts[2]).makeOffer(custom1155.address, 1, sales.sales[0].seller, 1, nftPrice.toString(), nftEndPrice.toString(), sales.sales[0].startedAt, 1000, offerPrice2, 2, {
      from: accounts[2].address,
      value: offerPrice2.mul(2)
    })).wait()
    afterBalance = await accounts[2].getBalance()
    expect(prevBalance.sub(txRes.cumulativeGasUsed.mul(txRes.effectiveGasPrice))).to.equal(afterBalance.add(offerPrice2.mul(2)))
    let sale = await marketplace.getSale(custom1155.address, 1, sales.sales[0].seller, 1, nftPrice.toString(), nftEndPrice.toString(), sales.sales[0].startedAt, 1000, 2)
    expect(sale.sale.offerers.length).to.equal(2)
    expect(sale.sale.offerers[0]).to.equal(accounts[1].address)
    expect(sale.sale.offerers[1]).to.equal(accounts[2].address)
    expect(sale.sale.offerPrices[0]).to.equal(offerPrice1)
    expect(sale.sale.offerPrices[1]).to.equal(offerPrice2)
    expect(sale.sale.offerAmounts[0].toString()).to.equal('2')
    expect(sale.sale.offerAmounts[1].toString()).to.equal('2')
    prevBalance = await accounts[1].getBalance();
    txRes = await (await marketplace.connect(accounts[1]).cancelOffer(sales.sales[0].seller, custom1155.address, 1, 1, nftPrice.toString(), nftEndPrice.toString(), sales.sales[0].startedAt, 1000, 2)).wait()
    afterBalance = await accounts[1].getBalance();
    expect(afterBalance.add(txRes.cumulativeGasUsed.mul(txRes.effectiveGasPrice))).to.equal(prevBalance.add(offerPrice1.mul(2)))
    sale = await marketplace.getSale(custom1155.address, 1, sales.sales[0].seller, 1, nftPrice.toString(), nftEndPrice.toString(), sales.sales[0].startedAt, 1000, 2)
    expect(sale.sale.offerers.length).to.equal(1)
    expect(sale.sale.offerers[0]).to.equal(accounts[2].address)
    expect(sale.sale.offerPrices[0]).to.equal(offerPrice2)
    expect(sale.sale.offerAmounts[0].toString()).to.equal('2')
    let claimable = await marketplace.getClaimable(accounts[1].address, 1)
    expect(claimable.toString()).to.equal('0')
    await (await marketplace.connect(accounts[0]).cancelSale(custom1155.address, 1, sales.sales[0].seller, 1, sales.sales[0].startPrice, sales.sales[0].endPrice, 5, sales.sales[0].startedAt, sales.sales[0].duration)).wait()
    claimable = await marketplace.getClaimable(accounts[2].address, 1)
    expect(claimable).to.equal(offerPrice2.mul(2))
    prevBalance = await accounts[2].getBalance()
    txRes = await (await marketplace.connect(accounts[2]).claim(claimable, 1)).wait()
    claimable = await marketplace.getClaimable(accounts[2].address, 1)
    afterBalance = await accounts[2].getBalance()
    expect(offerPrice2.mul(2).sub(txRes.cumulativeGasUsed.mul(txRes.effectiveGasPrice))).to.equal(afterBalance.sub(prevBalance))
  })
  it('Create Sale, Create Offer and Accept Offer with Verified ERC1155 NFT Smart Contract', async () => {
    await (await marketplace.connect(accounts[0]).setAddressesContractAddr(addresses.address)).wait()
    await (await addresses.add(custom1155.address)).wait()
    await (await addresses.verify(custom1155.address)).wait()
    let saleTokens = await marketplace.getSaleTokens(custom1155.address)
    expect(saleTokens.length).to.equal(0)
    let saleTokensBySeller = await marketplace.getSaleTokensBySeller(custom1155.address, accounts[0].address)
    expect(saleTokensBySeller.length).to.equal(0)
    let sales = await marketplace.getSalesByNFT(custom1155.address, 1)
    expect(sales.sales.length).to.equal(0)
    let salesBySellerNFT = await marketplace.getSalesBySellerNFT(accounts[0].address, custom1155.address, 1)
    expect(salesBySellerNFT.sales.length).to.equal(0)
    await (await marketplace.connect(accounts[0]).createSale(custom1155.address, 1, 1, nftPrice.toString(), nftEndPrice.toString(), 1000, 5)).wait()
    expect(await custom1155.balanceOf(accounts[0].address, 1)).to.equal(5)
    sales = await marketplace.getSalesByNFT(custom1155.address, 1)
    expect(sales.sales.length).to.equal(1)
    expect(sales.sales[0].payment.toString()).to.equal('1')
    expect(sales.sales[0].seller).to.equal(accounts[0].address)
    expect(sales.sales[0].startPrice.toString()).to.equal(nftPrice.toString())
    expect(sales.sales[0].endPrice.toString()).to.equal(nftEndPrice.toString())
    expect(sales.sales[0].amount.toString()).to.equal('5')
    expect(sales.sales[0].duration.toString()).to.equal('1000')
    let prevBalance = await accounts[1].getBalance()
    let txRes = await (await marketplace.connect(accounts[1]).makeOffer(custom1155.address, 1, sales.sales[0].seller, 1, nftPrice.toString(), nftEndPrice.toString(), sales.sales[0].startedAt, 1000, offerPrice1, 5, {
      from: accounts[1].address,
      value: offerPrice1.mul(5)
    })).wait()
    let afterBalance = await accounts[1].getBalance()
    expect(prevBalance.sub(txRes.cumulativeGasUsed.mul(txRes.effectiveGasPrice))).to.equal(afterBalance.add(offerPrice1.mul(5)))
    prevBalance = await accounts[2].getBalance()
    txRes = await (await marketplace.connect(accounts[2]).makeOffer(custom1155.address, 1, sales.sales[0].seller, 1, nftPrice.toString(), nftEndPrice.toString(), sales.sales[0].startedAt, 1000, offerPrice2, 2, {
      from: accounts[2].address,
      value: offerPrice2.mul(2)
    })).wait()
    afterBalance = await accounts[2].getBalance()
    expect(prevBalance.sub(txRes.cumulativeGasUsed.mul(txRes.effectiveGasPrice))).to.equal(afterBalance.add(offerPrice2.mul(2)))
    let sale = await marketplace.getSale(custom1155.address, 1, sales.sales[0].seller, 1, nftPrice.toString(), nftEndPrice.toString(), sales.sales[0].startedAt, 1000, 2)
    expect(sale.sale.offerers.length).to.equal(2)
    expect(sale.sale.amount.toString()).to.equal('5')
    expect(sale.sale.offerers[0]).to.equal(accounts[1].address)
    expect(sale.sale.offerers[1]).to.equal(accounts[2].address)
    expect(sale.sale.offerPrices[0]).to.equal(offerPrice1)
    expect(sale.sale.offerPrices[1]).to.equal(offerPrice2)
    expect(sale.sale.offerAmounts[0].toString()).to.equal('5')
    expect(sale.sale.offerAmounts[1].toString()).to.equal('2')
    let prevSellerBalance = await accounts[0].getBalance()
    txRes = await (await marketplace.connect(accounts[0]).acceptOffer(sales.sales[0].seller, custom1155.address, 1, 1, nftPrice.toString(), nftEndPrice.toString(), sales.sales[0].startedAt, 1000, 2)).wait()
    let afterSellerBalance = await accounts[0].getBalance()
    expect(offerPrice2.mul(2).sub(txRes.cumulativeGasUsed.mul(txRes.effectiveGasPrice))).to.equal(afterSellerBalance.sub(prevSellerBalance))
    const claimable = await marketplace.getClaimable(accounts[1].address, 1)
    expect(claimable).to.equal(offerPrice1.mul(2))
    sale = await marketplace.getSale(custom1155.address, 1, sales.sales[0].seller, 1, nftPrice.toString(), nftEndPrice.toString(), sales.sales[0].startedAt, 1000, 2)
    expect(sale.sale.offerers.length).to.equal(1)
    expect(sale.sale.amount.toString()).to.equal('3')
    expect(sale.sale.offerers[0]).to.equal(accounts[1].address)
    expect(sale.sale.offerPrices[0]).to.equal(offerPrice1)
    expect(sale.sale.offerAmounts[0].toString()).to.equal('3')
    prevSellerBalance = await accounts[0].getBalance()
    txRes = await (await marketplace.connect(accounts[0]).acceptOffer(sales.sales[0].seller, custom1155.address, 1, 1, nftPrice.toString(), nftEndPrice.toString(), sales.sales[0].startedAt, 1000, 3)).wait()
    afterSellerBalance = await accounts[0].getBalance()
    expect(offerPrice1.mul(3).sub(txRes.cumulativeGasUsed.mul(txRes.effectiveGasPrice))).to.equal(afterSellerBalance.sub(prevSellerBalance))
    saleTokens = await marketplace.getSaleTokens(custom1155.address)
    expect(saleTokens.length).to.equal(0)
  })

  it('Create Sale and Purchase Sale by Spark Token with Verified ERC1155 NFT Smart Contract', async () => {
    await (await sparkToken.connect(accounts[3]).setDistributionTeamsAddresses(accounts[3].address, accounts[3].address, accounts[3].address, accounts[3].address, accounts[3].address, accounts[3].address, accounts[3].address, accounts[3].address, accounts[3].address, accounts[3].address)).wait()
    await (await sparkToken.connect(accounts[3]).distributeTokens()).wait()
    let sellerPrevBalance = await sparkToken.balanceOf(accounts[0].address)
    expect(sellerPrevBalance.toString()).to.equal('0')
    await (await sparkToken.connect(accounts[3]).transfer(accounts[1].address, nftPrice.mul(2))).wait()
    let buyerPrevBalance = await sparkToken.balanceOf(accounts[1].address)
    expect(buyerPrevBalance).to.equal(nftPrice.mul(2))
    await (await marketplace.connect(accounts[0]).setAddressesContractAddr(addresses.address)).wait()
    await (await addresses.add(custom1155.address)).wait()
    await (await addresses.verify(custom1155.address)).wait()
    let saleTokens = await marketplace.getSaleTokens(custom1155.address)
    expect(saleTokens.length).to.equal(0)
    let saleTokensBySeller = await marketplace.getSaleTokensBySeller(custom1155.address, accounts[0].address)
    expect(saleTokensBySeller.length).to.equal(0)
    let sales = await marketplace.getSalesByNFT(custom1155.address, 1)
    expect(sales.sales.length).to.equal(0)
    let salesBySellerNFT = await marketplace.getSalesBySellerNFT(accounts[0].address, custom1155.address, 1)
    expect(salesBySellerNFT.sales.length).to.equal(0)
    await (await marketplace.connect(accounts[0]).createSale(custom1155.address, 1, 2, nftPrice.toString(), nftEndPrice.toString(), 1000, 5)).wait()
    expect(await custom1155.balanceOf(accounts[0].address, 1)).to.equal(5)
    sales = await marketplace.getSalesByNFT(custom1155.address, 1)
    expect(sales.sales.length).to.equal(1)
    expect(sales.sales[0].payment.toString()).to.equal('2')
    expect(sales.sales[0].seller).to.equal(accounts[0].address)
    expect(sales.sales[0].startPrice.toString()).to.equal(nftPrice.toString())
    expect(sales.sales[0].endPrice.toString()).to.equal(nftEndPrice.toString())
    expect(sales.sales[0].amount.toString()).to.equal('5')
    expect(sales.sales[0].duration.toString()).to.equal('1000')
    saleTokens = await marketplace.getSaleTokens(custom1155.address)
    expect(saleTokens.length).to.equal(1)
    expect(saleTokens[0]).to.equal('1')
    saleTokensBySeller = await marketplace.getSaleTokensBySeller(custom1155.address, accounts[0].address)
    expect(saleTokensBySeller.length).to.equal(1)
    expect(saleTokensBySeller[0]).to.equal('1')
    let currentPrice = await marketplace.getCurrentPrice(custom1155.address, 1, { payment: 2, seller: sales.sales[0].seller, startPrice: sales.sales[0].startPrice, endPrice: sales.sales[0].endPrice, amount: 1, startedAt: sales.sales[0].startedAt, duration: sales.sales[0].duration })
    expect(currentPrice.lte(nftPrice)).to.equal(true)
    expect(currentPrice.gte(nftEndPrice)).to.equal(true)
    await (await sparkToken.connect(accounts[1]).approve(marketplace.address, currentPrice.mul(2))).wait()
    let buyRes = await (await marketplace.connect(accounts[1]).buy(custom1155.address, 1, sales.sales[0].seller, 2, sales.sales[0].startPrice, sales.sales[0].endPrice, 2, sales.sales[0].startedAt, sales.sales[0].duration)).wait()
    let saleSuccessEvent = buyRes.events.find(event => event.event === 'SaleSuccessful')
    let sellerAfterBalance = await sparkToken.balanceOf(accounts[0].address)
    let buyerAfterBalance = await sparkToken.balanceOf(accounts[1].address)
    expect(sellerAfterBalance.sub(sellerPrevBalance).eq(saleSuccessEvent.args.price)).to.equal(true)
    expect(buyerPrevBalance.sub(buyerAfterBalance).eq(saleSuccessEvent.args.price)).to.equal(true)
    expect(await custom1155.balanceOf(accounts[1].address, 1)).to.equal(2)
  })

  it('Create Sale, Create Offer and Accept Offer by Spark Token with Verified ERC1155 NFT Smart Contract', async () => {
    await (await sparkToken.connect(accounts[3]).setDistributionTeamsAddresses(accounts[3].address, accounts[3].address, accounts[3].address, accounts[3].address, accounts[3].address, accounts[3].address, accounts[3].address, accounts[3].address, accounts[3].address, accounts[3].address)).wait()
    await (await sparkToken.connect(accounts[3]).distributeTokens()).wait()
    await (await sparkToken.connect(accounts[3]).transfer(accounts[1].address, offerPrice1.mul(5))).wait()
    await (await sparkToken.connect(accounts[3]).transfer(accounts[2].address, offerPrice2.mul(2))).wait()
    await (await marketplace.connect(accounts[0]).setAddressesContractAddr(addresses.address)).wait()
    await (await addresses.add(custom1155.address)).wait()
    await (await addresses.verify(custom1155.address)).wait()
    let saleTokens = await marketplace.getSaleTokens(custom1155.address)
    expect(saleTokens.length).to.equal(0)
    let saleTokensBySeller = await marketplace.getSaleTokensBySeller(custom1155.address, accounts[0].address)
    expect(saleTokensBySeller.length).to.equal(0)
    let sales = await marketplace.getSalesByNFT(custom1155.address, 1)
    expect(sales.sales.length).to.equal(0)
    let salesBySellerNFT = await marketplace.getSalesBySellerNFT(accounts[0].address, custom1155.address, 1)
    expect(salesBySellerNFT.sales.length).to.equal(0)
    await (await marketplace.connect(accounts[0]).createSale(custom1155.address, 1, 2, nftPrice.toString(), nftEndPrice.toString(), 1000, 5)).wait()
    expect(await custom1155.balanceOf(accounts[0].address, 1)).to.equal(5)
    sales = await marketplace.getSalesByNFT(custom1155.address, 1)
    expect(sales.sales.length).to.equal(1)
    expect(sales.sales[0].payment.toString()).to.equal('2')
    expect(sales.sales[0].seller).to.equal(accounts[0].address)
    expect(sales.sales[0].startPrice.toString()).to.equal(nftPrice.toString())
    expect(sales.sales[0].endPrice.toString()).to.equal(nftEndPrice.toString())
    expect(sales.sales[0].amount.toString()).to.equal('5')
    expect(sales.sales[0].duration.toString()).to.equal('1000')
    let prevBalance = await sparkToken.balanceOf(accounts[1].address)
    await (await sparkToken.connect(accounts[1]).approve(marketplace.address, offerPrice1.mul(5))).wait()
    let txRes = await (await marketplace.connect(accounts[1]).makeOffer(custom1155.address, 1, sales.sales[0].seller, 2, nftPrice.toString(), nftEndPrice.toString(), sales.sales[0].startedAt, 1000, offerPrice1, 5)).wait()
    let afterBalance = await sparkToken.balanceOf(accounts[1].address)
    expect(prevBalance).to.equal(afterBalance.add(offerPrice1.mul(5)))
    prevBalance = await sparkToken.balanceOf(accounts[2].address)
    await (await sparkToken.connect(accounts[2]).approve(marketplace.address, offerPrice2.mul(2))).wait()
    txRes = await (await marketplace.connect(accounts[2]).makeOffer(custom1155.address, 1, sales.sales[0].seller, 2, nftPrice.toString(), nftEndPrice.toString(), sales.sales[0].startedAt, 1000, offerPrice2, 2)).wait()
    afterBalance = await sparkToken.balanceOf(accounts[2].address)
    expect(prevBalance).to.equal(afterBalance.add(offerPrice2.mul(2)))
    let sale = await marketplace.getSale(custom1155.address, 1, sales.sales[0].seller, 2, nftPrice.toString(), nftEndPrice.toString(), sales.sales[0].startedAt, 1000, 2)
    expect(sale.sale.offerers.length).to.equal(2)
    expect(sale.sale.amount.toString()).to.equal('5')
    expect(sale.sale.offerers[0]).to.equal(accounts[1].address)
    expect(sale.sale.offerers[1]).to.equal(accounts[2].address)
    expect(sale.sale.offerPrices[0]).to.equal(offerPrice1)
    expect(sale.sale.offerPrices[1]).to.equal(offerPrice2)
    expect(sale.sale.offerAmounts[0].toString()).to.equal('5')
    expect(sale.sale.offerAmounts[1].toString()).to.equal('2')
    let prevSellerBalance = await sparkToken.balanceOf(accounts[0].address)
    txRes = await (await marketplace.connect(accounts[0]).acceptOffer(sales.sales[0].seller, custom1155.address, 1, 2, nftPrice.toString(), nftEndPrice.toString(), sales.sales[0].startedAt, 1000, 2)).wait()
    let afterSellerBalance = await sparkToken.balanceOf(accounts[0].address)
    expect(offerPrice2.mul(2)).to.equal(afterSellerBalance.sub(prevSellerBalance))
    const claimable = await marketplace.getClaimable(accounts[1].address, 2)
    expect(claimable).to.equal(offerPrice1.mul(2))
    sale = await marketplace.getSale(custom1155.address, 1, sales.sales[0].seller, 2, nftPrice.toString(), nftEndPrice.toString(), sales.sales[0].startedAt, 1000, 2)
    expect(sale.sale.offerers.length).to.equal(1)
    expect(sale.sale.amount.toString()).to.equal('3')
    expect(sale.sale.offerers[0]).to.equal(accounts[1].address)
    expect(sale.sale.offerPrices[0]).to.equal(offerPrice1)
    expect(sale.sale.offerAmounts[0].toString()).to.equal('3')
    prevSellerBalance = await sparkToken.balanceOf(accounts[0].address)
    await (await marketplace.connect(accounts[0]).acceptOffer(sales.sales[0].seller, custom1155.address, 1, 2, nftPrice.toString(), nftEndPrice.toString(), sales.sales[0].startedAt, 1000, 3)).wait()
    afterSellerBalance = await sparkToken.balanceOf(accounts[0].address)
    expect(offerPrice1.mul(3)).to.equal(afterSellerBalance.sub(prevSellerBalance))
    saleTokens = await marketplace.getSaleTokens(custom1155.address)
    expect(saleTokens.length).to.equal(0)
    prevBalance = await sparkToken.balanceOf(accounts[1].address)
    await (await marketplace.connect(accounts[1]).claim(claimable, 2)).wait()
    afterBalance = await sparkToken.balanceOf(accounts[1].address)
    expect(afterBalance.sub(prevBalance)).to.equal(claimable)
  })

  it('Create Auction, Create Bid and Cancel Auction with Verified ERC1155 NFT Smart Contract', async () => {
    await (await marketplace.connect(accounts[0]).setAddressesContractAddr(addresses.address)).wait()
    await (await addresses.add(custom1155.address)).wait()
    await (await addresses.verify(custom1155.address)).wait()
    let auctions = await marketplace.getAuctionsByNFT(custom1155.address, 1)
    expect(auctions.length).to.equal(0)
    auctions = await marketplace.getAuctionsBySellerNFT(accounts[0].address, custom1155.address, 1)
    expect(auctions.length).to.equal(0)
    await (await marketplace.connect(accounts[0]).createAuction(custom1155.address, 1, 1, 5)).wait()
    expect(await custom1155.balanceOf(accounts[0].address, 1)).to.equal(5)
    auctions = await marketplace.getAuctionsByNFT(custom1155.address, 1)
    const startedAt = auctions[0].startedAt
    let prevBalance = await accounts[1].getBalance()
    let txRes = await (await marketplace.connect(accounts[1]).bid(custom1155.address, 1, accounts[0].address, startedAt, 5, offerPrice1, {
      from: accounts[1].address,
      value: offerPrice1.mul(5)
    })).wait()
    let afterBalance = await accounts[1].getBalance()
    expect(prevBalance.sub(txRes.cumulativeGasUsed.mul(txRes.effectiveGasPrice))).to.equal(afterBalance.add(offerPrice1.mul(5)))
    prevBalance = await accounts[2].getBalance()
    txRes = await (await marketplace.connect(accounts[2]).bid(custom1155.address, 1, accounts[0].address, startedAt, 2, offerPrice2, {
      from: accounts[2].address,
      value: offerPrice2.mul(2)
    })).wait()
    afterBalance = await accounts[2].getBalance()
    expect(prevBalance.sub(txRes.cumulativeGasUsed.mul(txRes.effectiveGasPrice))).to.equal(afterBalance.add(offerPrice2.mul(2)))
    auctions = await marketplace.getAuctionsByNFT(custom1155.address, 1)
    expect(auctions.length).to.equal(1)
    expect(auctions[0].bidders.length).to.equal(2)
    expect(auctions[0].bidders[0]).to.equal(accounts[1].address)
    expect(auctions[0].bidPrices[0]).to.equal(offerPrice1)
    expect(auctions[0].bidAmounts[0].toString()).to.equal('5')
    expect(auctions[0].bidders[1]).to.equal(accounts[2].address)
    expect(auctions[0].bidPrices[1]).to.equal(offerPrice2)
    expect(auctions[0].bidAmounts[1].toString()).to.equal('2')
    auctions = await marketplace.getAuctionsBySellerNFT(accounts[0].address, custom1155.address, 1)
    expect(auctions.length).to.equal(1)
    expect(auctions[0].bidders.length).to.equal(2)
    expect(auctions[0].bidders[0]).to.equal(accounts[1].address)
    expect(auctions[0].bidPrices[0]).to.equal(offerPrice1)
    expect(auctions[0].bidAmounts[0].toString()).to.equal('5')
    expect(auctions[0].bidders[1]).to.equal(accounts[2].address)
    expect(auctions[0].bidPrices[1]).to.equal(offerPrice2)
    expect(auctions[0].bidAmounts[1].toString()).to.equal('2')
    prevBalance = await accounts[1].getBalance()
    txRes = await (await marketplace.connect(accounts[1]).cancelBid(custom1155.address, 1, accounts[0].address, startedAt, 2)).wait()
    afterBalance = await accounts[1].getBalance()
    expect(afterBalance.add(txRes.cumulativeGasUsed.mul(txRes.effectiveGasPrice))).to.equal(prevBalance.add(offerPrice1.mul(2)))
    auctions = await marketplace.getAuctionsByNFT(custom1155.address, 1)
    expect(auctions.length).to.equal(1)
    expect(auctions[0].bidders.length).to.equal(2)
    expect(auctions[0].bidders[0]).to.equal(accounts[1].address)
    expect(auctions[0].bidPrices[0]).to.equal(offerPrice1)
    expect(auctions[0].bidAmounts[0].toString()).to.equal('3')
    expect(auctions[0].bidders[1]).to.equal(accounts[2].address)
    expect(auctions[0].bidPrices[1]).to.equal(offerPrice2)
    expect(auctions[0].bidAmounts[1].toString()).to.equal('2')
    auctions = await marketplace.getAuctionsBySellerNFT(accounts[0].address, custom1155.address, 1)
    expect(auctions.length).to.equal(1)
    expect(auctions[0].bidders.length).to.equal(2)
    expect(auctions[0].bidders[0]).to.equal(accounts[1].address)
    expect(auctions[0].bidPrices[0]).to.equal(offerPrice1)
    expect(auctions[0].bidAmounts[0].toString()).to.equal('3')
    expect(auctions[0].bidders[1]).to.equal(accounts[2].address)
    expect(auctions[0].bidPrices[1]).to.equal(offerPrice2)
    expect(auctions[0].bidAmounts[1].toString()).to.equal('2')
    prevBalance = await accounts[1].getBalance()
    txRes = await (await marketplace.connect(accounts[1]).cancelBid(custom1155.address, 1, accounts[0].address, startedAt, 3)).wait()
    afterBalance = await accounts[1].getBalance()
    expect(afterBalance.add(txRes.cumulativeGasUsed.mul(txRes.effectiveGasPrice))).to.equal(prevBalance.add(offerPrice1.mul(3)))
    auctions = await marketplace.getAuctionsByNFT(custom1155.address, 1)
    expect(auctions.length).to.equal(1)
    expect(auctions[0].bidders.length).to.equal(1)
    expect(auctions[0].bidders[0]).to.equal(accounts[2].address)
    expect(auctions[0].bidPrices[0]).to.equal(offerPrice2)
    expect(auctions[0].bidAmounts[0].toString()).to.equal('2')
    auctions = await marketplace.getAuctionsBySellerNFT(accounts[0].address, custom1155.address, 1)
    expect(auctions.length).to.equal(1)
    expect(auctions[0].bidders.length).to.equal(1)
    expect(auctions[0].bidders[0]).to.equal(accounts[2].address)
    expect(auctions[0].bidPrices[0]).to.equal(offerPrice2)
    expect(auctions[0].bidAmounts[0].toString()).to.equal('2')
    await (await marketplace.connect(accounts[0]).cancelAuction(custom1155.address, 1, startedAt, 4)).wait()
    auctions = await marketplace.getAuctionsByNFT(custom1155.address, 1)
    expect(auctions.length).to.equal(1)
    expect(auctions[0].amount.toString()).to.equal('1')
    expect(auctions[0].bidders.length).to.equal(1)
    expect(auctions[0].bidders[0]).to.equal(accounts[2].address)
    expect(auctions[0].bidPrices[0]).to.equal(offerPrice2)
    expect(auctions[0].bidAmounts[0].toString()).to.equal('1')
    auctions = await marketplace.getAuctionsBySellerNFT(accounts[0].address, custom1155.address, 1)
    expect(auctions.length).to.equal(1)
    expect(auctions[0].amount.toString()).to.equal('1')
    expect(auctions[0].bidders.length).to.equal(1)
    expect(auctions[0].bidders[0]).to.equal(accounts[2].address)
    expect(auctions[0].bidPrices[0]).to.equal(offerPrice2)
    expect(auctions[0].bidAmounts[0].toString()).to.equal('1')
    expect(await marketplace.getClaimable(accounts[2].address, 1)).to.equal(offerPrice2)
    await (await marketplace.connect(accounts[0]).cancelAuction(custom1155.address, 1, startedAt, 1)).wait()
    auctions = await marketplace.getAuctionsByNFT(custom1155.address, 1)
    expect(auctions.length).to.equal(0)
    auctions = await marketplace.getAuctionsBySellerNFT(accounts[0].address, custom1155.address, 1)
    expect(auctions.length).to.equal(0)
    expect(await marketplace.getClaimable(accounts[2].address, 1)).to.equal(offerPrice2.mul(2))
  })

  it('Create Auction, Create Bid and Accept Bid with Verified ERC1155 NFT Smart Contract', async () => {
    await (await marketplace.connect(accounts[0]).setAddressesContractAddr(addresses.address)).wait()
    await (await addresses.add(custom1155.address)).wait()
    await (await addresses.verify(custom1155.address)).wait()
    let auctions = await marketplace.getAuctionsByNFT(custom1155.address, 1)
    expect(auctions.length).to.equal(0)
    auctions = await marketplace.getAuctionsBySellerNFT(accounts[0].address, custom1155.address, 1)
    expect(auctions.length).to.equal(0)
    await (await marketplace.connect(accounts[0]).createAuction(custom1155.address, 1, 1, 5)).wait()
    expect(await custom1155.balanceOf(accounts[0].address, 1)).to.equal(5)
    auctions = await marketplace.getAuctionsByNFT(custom1155.address, 1)
    const startedAt = auctions[0].startedAt
    let prevBalance = await accounts[1].getBalance()
    let txRes = await (await marketplace.connect(accounts[1]).bid(custom1155.address, 1, accounts[0].address, startedAt, 5, offerPrice1, {
      from: accounts[1].address,
      value: offerPrice1.mul(5)
    })).wait()
    let afterBalance = await accounts[1].getBalance()
    expect(prevBalance.sub(txRes.cumulativeGasUsed.mul(txRes.effectiveGasPrice))).to.equal(afterBalance.add(offerPrice1.mul(5)))
    prevBalance = await accounts[2].getBalance()
    txRes = await (await marketplace.connect(accounts[2]).bid(custom1155.address, 1, accounts[0].address, startedAt, 2, offerPrice2, {
      from: accounts[2].address,
      value: offerPrice2.mul(2)
    })).wait()
    afterBalance = await accounts[2].getBalance()
    expect(prevBalance.sub(txRes.cumulativeGasUsed.mul(txRes.effectiveGasPrice))).to.equal(afterBalance.add(offerPrice2.mul(2)))
    auctions = await marketplace.getAuctionsByNFT(custom1155.address, 1)
    expect(auctions.length).to.equal(1)
    expect(auctions[0].bidders.length).to.equal(2)
    expect(auctions[0].bidders[0]).to.equal(accounts[1].address)
    expect(auctions[0].bidPrices[0]).to.equal(offerPrice1)
    expect(auctions[0].bidAmounts[0].toString()).to.equal('5')
    expect(auctions[0].bidders[1]).to.equal(accounts[2].address)
    expect(auctions[0].bidPrices[1]).to.equal(offerPrice2)
    expect(auctions[0].bidAmounts[1].toString()).to.equal('2')
    auctions = await marketplace.getAuctionsBySellerNFT(accounts[0].address, custom1155.address, 1)
    expect(auctions.length).to.equal(1)
    expect(auctions[0].bidders.length).to.equal(2)
    expect(auctions[0].bidders[0]).to.equal(accounts[1].address)
    expect(auctions[0].bidPrices[0]).to.equal(offerPrice1)
    expect(auctions[0].bidAmounts[0].toString()).to.equal('5')
    expect(auctions[0].bidders[1]).to.equal(accounts[2].address)
    expect(auctions[0].bidPrices[1]).to.equal(offerPrice2)
    expect(auctions[0].bidAmounts[1].toString()).to.equal('2')
    prevBalance = await accounts[0].getBalance()
    txRes = await (await marketplace.connect(accounts[0]).acceptBid(custom1155.address, 1, startedAt, 2)).wait()
    afterBalance = await accounts[0].getBalance()
    expect(afterBalance.add(txRes.cumulativeGasUsed.mul(txRes.effectiveGasPrice))).to.equal(prevBalance.add(offerPrice2.mul(2)))
    expect(await custom1155.balanceOf(accounts[2].address, 1)).to.equal('2')
    auctions = await marketplace.getAuctionsByNFT(custom1155.address, 1)
    expect(auctions.length).to.equal(1)
    expect(auctions[0].bidders.length).to.equal(1)
    expect(auctions[0].bidders[0]).to.equal(accounts[1].address)
    expect(auctions[0].bidPrices[0]).to.equal(offerPrice1)
    expect(auctions[0].bidAmounts[0].toString()).to.equal('3')
    auctions = await marketplace.getAuctionsBySellerNFT(accounts[0].address, custom1155.address, 1)
    expect(auctions.length).to.equal(1)
    expect(auctions[0].bidders.length).to.equal(1)
    expect(auctions[0].bidders[0]).to.equal(accounts[1].address)
    expect(auctions[0].bidPrices[0]).to.equal(offerPrice1)
    expect(auctions[0].bidAmounts[0].toString()).to.equal('3')
    expect(await marketplace.getClaimable(accounts[1].address, 1)).to.equal(offerPrice1.mul(2))
    prevBalance = await accounts[0].getBalance()
    txRes = await (await marketplace.connect(accounts[0]).acceptBid(custom1155.address, 1, startedAt, 3)).wait()
    afterBalance = await accounts[0].getBalance()
    expect(afterBalance.add(txRes.cumulativeGasUsed.mul(txRes.effectiveGasPrice))).to.equal(prevBalance.add(offerPrice1.mul(3)))
    expect(await custom1155.balanceOf(accounts[1].address, 1)).to.equal('3')
    auctions = await marketplace.getAuctionsByNFT(custom1155.address, 1)
    expect(auctions.length).to.equal(0)
    auctions = await marketplace.getAuctionsBySellerNFT(accounts[0].address, custom1155.address, 1)
    expect(auctions.length).to.equal(0)
  })
})
